name: build

# This should ensure that the workflow won't run on `feat/*`, `fix/*` and `chore/*` branches, but will
# otherwise execute on any other branch and any pull request.
on:
  push:
    branches-ignore:
      - '**/feat/*'
      - '**/fix/*'
      - '**/chore/*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    uses: sybila/github-workflows/.github/workflows/rust-z3-build-and-check.yml@main
    with:
      z3-version: "4.13.3"
      rust-version: "1.90.0"
      min-rust-version: "1.88.0"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}